<?
$PERM["test.php"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["12"]="T_8";
$PERM["useful"]["*"]="R";
$PERM["reviews"]["*"]="D";
$PERM["/"]["6"]="X";
$PERM["/"]["*"]="R";
?>